export enum CardId {
  // SYSTEM (nie są kartami w UI)
  ANALYSIS = "ANALYSIS",
  CITY_REPORT = "CITY_REPORT",

  // TAJNE (gracz nie może mówić)
  CHECK = "CHECK",
  LINK = "LINK",
  BEHAVIOR_SCAN = "BEHAVIOR_SCAN",
  SHADOW = "SHADOW",
  FALSE_TRACE = "FALSE_TRACE",
  DISRUPTION_PASSIVE = "DISRUPTION_PASSIVE",

  // JAWNE
  SHIELD = "SHIELD",
  DOUBLE_VOTE = "DOUBLE_VOTE",
  ALIBI = "ALIBI",
  SILENCE = "SILENCE",
  RESET_SUSPICION = "RESET_SUSPICION",
  LAST_WORD = "LAST_WORD",

  // TYLKO MAFIA
  REPORT_DISRUPTION = "REPORT_DISRUPTION"
}
