export enum Phase {
  LOBBY = "LOBBY",

  INIT_SILENCE = "INIT_SILENCE",
  INIT_VOTE = "INIT_VOTE",
  INIT_TOP_SPEECH = "INIT_TOP_SPEECH",

  NIGHT = "NIGHT",

  DAY_DEBATE = "DAY_DEBATE",
  DAY_VOTE = "DAY_VOTE",

  GAME_OVER = "GAME_OVER"
}
